### ISSUE TITLE
kubectl get pods gives: "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by jonalv** [kubenow/KubeNow#180]
Running version 0.2.1 on SSC I get this error:

```
$ kubectl get pods
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x15e0280, 0xc42000e0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/client/typed/discovery.apiVersionsToAPIGroup(0xc4203eb590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20c9608, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/typed/discovery/discovery_client.go:111 +0x222
k8s.io/kubernetes/pkg/client/typed/discovery.(*DiscoveryClient).ServerGroups(0xc4203c37a0, 0xc4203eb4f0, 0x43, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/typed/discovery/discovery_client.go:123 +0x5ee
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*CachedDiscoveryClient).ServerGroups(0xc4201eb780, 0x4, 0x0, 0x6)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/cached_discovery.go:117 +0x11a
k8s.io/kubernetes/pkg/client/typed/discovery.GetAPIGroupResources(0x7f0cb1f39650, 0xc4201eb780, 0xc4201eb780, 0x7f0cb1f39650, 0xc4201eb780, 0xceae16, 0x1543fc0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/typed/discovery/restmapper.go:115 +0x5f
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*factory).UnstructuredObject(0xc4203c4120, 0x178417d, 0x9, 0x0, 0x0, 0xfa4f8211941a5c44, 0x4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:380 +0x9c
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0x205ed60, 0xc4203c4120, 0x2046000, 0xc420022010, 0x2046000, 0xc420022018, 0xc420481440, 0xc42041d500, 0x1, 0x1, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:152 +0x13d
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc420481440, 0xc42041d500, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:105 +0x95
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420481440, 0xc42041d490, 0x1, 0x1, 0xc420481440, 0xc42041d490)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420182240, 0xc42041d0f0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420182240, 0xc4203c4120, 0x2045fc0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:38 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
```

**Comment by jonalv** [comment]
Confirmed on gce as well

**Comment by mcapuccini** [comment]
could you run: `ansible-playbook playbooks/infra-test.yml` and post the result?

**Comment by mcapuccini** [comment]
please run: `git status` and post the results as well.

**Comment by jonalv** [comment]
```
$ git status
HEAD detached at 0.2.1
```

**Comment by jonalv** [comment]
Oh found out what I was doing wrong. I was accidentally using the edge node instead of the master node
